name: main

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Site1
        run: |
          cd site1
          npm ci
          npm run build

      - name: Site2
        run: |
          cd site2
          npm ci
          npm run build

  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Prettier
        run: npm i prettier --no-save

      - name: Prettify
        run: npx prettier --check .
